.equ BIN_SIZE, 3145728
.word 0xB8623615                        # BHASH0
.word 0x981F578B                        # BHASH1
.word 0xCDCAA182                        # BHASH2
.word 0xCFFD9910                        # BHASH3
.word 0xC7FC60EB                        # BHASH4
.word 0x28BB5B53                        # BHASH5
.word 0xD9DBF4E9                        # BHASH6
.word 0xC120B2D9                        # BHASH7
